-- MySQL Script generated by MySQL Workbench
-- Sat May 23 13:25:26 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema hackingrio
-- -----------------------------------------------------
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`empresas_gerais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empresas_gerais` (
  `id` INT NOT NULL,
  `nomeFantasia` VARCHAR(45) NOT NULL,
  `setor` VARCHAR(45) NOT NULL,
  `cnpj` VARCHAR(45) NOT NULL,
  `cnae` VARCHAR(45) NOT NULL,
  `porteNominal` VARCHAR(45) NOT NULL,
  `faturamentoPresumido` DOUBLE NOT NULL,
  `quantidadeFuncionarios` INT NOT NULL,
  `capitalSocial` DOUBLE NOT NULL,
  `createTime` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `updateTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empresas_endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empresas_endereco` (
  `cep` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `empresas_gerais_id` INT NOT NULL,
  PRIMARY KEY (`empresas_gerais_id`),
  CONSTRAINT `fk_empresas_endereco_empresas_gerais1`
    FOREIGN KEY (`empresas_gerais_id`)
    REFERENCES `mydb`.`empresas_gerais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empresas_socios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empresas_socios` (
  `nome` VARCHAR(50) NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `empresas_gerais_id` INT NOT NULL,
  PRIMARY KEY (`empresas_gerais_id`),
  CONSTRAINT `fk_empresas_socios_empresas_gerais1`
    FOREIGN KEY (`empresas_gerais_id`)
    REFERENCES `mydb`.`empresas_gerais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`empresas_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empresas_login` (
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `ultimoLogin` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `empresas_gerais_id` INT NOT NULL,
  PRIMARY KEY (`empresas_gerais_id`),
  CONSTRAINT `fk_empresas_login_empresas_gerais1`
    FOREIGN KEY (`empresas_gerais_id`)
    REFERENCES `mydb`.`empresas_gerais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`empresas_descricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`empresas_descricao` (
  `descricao` LONGTEXT NOT NULL,
  `logo` VARCHAR(45) NOT NULL,
  `empresas_gerais_id` INT NOT NULL,
  PRIMARY KEY (`empresas_gerais_id`),
  CONSTRAINT `fk_empresas_descricao_empresas_gerais1`
    FOREIGN KEY (`empresas_gerais_id`)
    REFERENCES `mydb`.`empresas_gerais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionarios_cadastro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionarios_cadastro` (
  `id` INT NOT NULL,
  `sexo` INT NOT NULL,
  `nomeCompleto` VARCHAR(50) NOT NULL,
  `tipoTrabalho` VARCHAR(45) NOT NULL,
  `categoriaTrabalho` INT NOT NULL,
  `experienciaEmpresa` INT NOT NULL,
  `escolaridade` INT NOT NULL,
  `createTime` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `empresas_gerais_id` INT NOT NULL,
  PRIMARY KEY (`id`, `empresas_gerais_id`),
  INDEX `fk_funcionarios_cadastro_empresas_gerais1_idx` (`empresas_gerais_id` ASC) VISIBLE,
  CONSTRAINT `fk_funcionarios_cadastro_empresas_gerais1`
    FOREIGN KEY (`empresas_gerais_id`)
    REFERENCES `mydb`.`empresas_gerais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionarios_descricao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionarios_descricao` (
  `descricao` LONGTEXT NOT NULL,
  `funcionarios_cadastro_id` INT NOT NULL,
  PRIMARY KEY (`funcionarios_cadastro_id`),
  CONSTRAINT `fk_funcionarios_descricao_funcionarios_cadastro1`
    FOREIGN KEY (`funcionarios_cadastro_id`)
    REFERENCES `mydb`.`funcionarios_cadastro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionarios_curriculo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionarios_curriculo` (
  `curriculo` VARCHAR(45) NOT NULL,
  `createTime` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `updateTime` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `funcionarios_cadastro_id` INT NOT NULL,
  PRIMARY KEY (`funcionarios_cadastro_id`),
  CONSTRAINT `fk_funcionarios_curriculo_funcionarios_cadastro1`
    FOREIGN KEY (`funcionarios_cadastro_id`)
    REFERENCES `mydb`.`funcionarios_cadastro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`negociacao_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`negociacao_funcionario` (
  `id` INT NOT NULL,
  `idEmpresaSolicitante` INT NOT NULL,
  `valorProposta` DOUBLE NOT NULL,
  `inicioTrabalho` DATE NOT NULL,
  `fimTrabalho` DATE NOT NULL,
  `status` INT NOT NULL,
  `createTime` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `funcionarios_cadastro_id` INT NOT NULL,
  PRIMARY KEY (`id`, `funcionarios_cadastro_id`),
  INDEX `fk_negociacao_funcionario_funcionarios_cadastro1_idx` (`funcionarios_cadastro_id` ASC) VISIBLE,
  CONSTRAINT `fk_negociacao_funcionario_funcionarios_cadastro1`
    FOREIGN KEY (`funcionarios_cadastro_id`)
    REFERENCES `mydb`.`funcionarios_cadastro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`negociacao_chat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`negociacao_chat` (
  `id` INT NOT NULL,
  `idEmpresa` INT NOT NULL,
  `mensagem` MEDIUMTEXT NOT NULL,
  `createTime` TIMESTAMP NULL,
  `negociacao_funcionario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `negociacao_funcionario_id`),
  INDEX `fk_negociacao_chat_negociacao_funcionario1_idx` (`negociacao_funcionario_id` ASC) VISIBLE,
  CONSTRAINT `fk_negociacao_chat_negociacao_funcionario1`
    FOREIGN KEY (`negociacao_funcionario_id`)
    REFERENCES `mydb`.`negociacao_funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`negociacao_contrato_assinaturas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`negociacao_contrato_assinaturas` (
  `id` INT NOT NULL,
  `empresaFuncionario` TINYINT NOT NULL,
  `empresaContratante` TINYINT NOT NULL,
  `empresaFuncionario` TINYINT NOT NULL,
  `createTime` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `negociacao_funcionario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `negociacao_funcionario_id`),
  INDEX `fk_negociacao_contrato_assinaturas_negociacao_funcionario1_idx` (`negociacao_funcionario_id` ASC) VISIBLE,
  CONSTRAINT `fk_negociacao_contrato_assinaturas_negociacao_funcionario1`
    FOREIGN KEY (`negociacao_funcionario_id`)
    REFERENCES `mydb`.`negociacao_funcionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
